services:
  - type: web
    name: small-magellanic-cloud
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.mjs
    autoDeploy: true
    envVars:
      - key: SMC_MAIL_SMTP_BLOCKED
        value: render-free
